# Generated by Django 3.2 on 2021-06-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_stripe_customer_id'),
        ('subscriptions', '0002_auto_20210507_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(help_text='Stripe subscription Id for communicating with stripe.', max_length=255)),
                ('start_date', models.DateTimeField(help_text='The start date of the subscription.')),
                ('end_date', models.DateTimeField(help_text='The end date of the subscription.')),
                ('stripe_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Stripe invoice code.', max_length=255, null=True)),
                ('current_start', models.DateTimeField(help_text='The start date of current invoice period.', null=True)),
                ('current_end', models.DateTimeField(help_text='The end date of current invoice period.', null=True)),
                ('delivery_name', models.CharField(help_text='Name of person whom delivery is for.', max_length=255, null=True)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('town_or_city', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('stripe_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.stripesubscription')),
            ],
        ),
    ]
