# Generated by Django 3.2 on 2021-06-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_stripesubscription_cancel_at_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
