# Generated by Django 3.2 on 2021-05-05 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
